---
- name: Launch a few Centos VMs
  hosts: localhost

  tasks:
  - name: create Centos VMs
    ec2:
      region: us-east-1
      image: ami-4bf3d731
      instance_type: t2.micro
      wait: yes
      wait_timeout: 500
      count: 1
      instance_tags: 
        Owner: YOURNAMEHERE
        Name: VMNAMEHERE
      monitoring: no
      group: YOURSECURITYGROUPNAMEHERE
      vpc_subnet_id: YOURSUBNETIDHERE
      assign_public_ip: yes
      termination_protection: no
      keypair: YOURKEYPAIRHERE
    register: ec2_out

  - name: wait for vm to ready
    wait_for:
      port: 22
      host: "{{item.public_ip}}"
      timeout: 300
      state: started
    with_items: "{{ ec2_out.instances }}"

  - name: output IPs
    debug:
      msg: "System {{ item.dns_name }} with ip {{ item.public_ip}}"
    with_items: "{{ ec2_out.instances }}"

      # Modeled from  i-062f9a298dd4b40b6 (med-tower-skylight-s1-work)
      #vpc: vpc-07e51cc7f6604590f
      
      # Borrowed heavily from youtube tutorial https://youtu.be/VRO9ZdH6Cbg

      #
      
