---
- name: Launch a few Windows VMs
  hosts: localhost

  tasks:
  - name: create windows VMs
    ec2:
      region: us-east-1
      image: ami-0477b9335a5a75438
      instance_type: t3.medium
      wait: yes
      wait_timeout: 500
      count: 3
      instance_tags: 
        Owner: YOURNAMEHERE
        Name: VMNAMEHERE
      monitoring: no
      group: YOURSECURITYGROUPNAMEHERE
      vpc_subnet_id: YOURSUBNETIDHERE
      assign_public_ip: yes
      user_data: "{{ lookup('template', 'win_ec2_user_data.j2', template_vars=dict(vm_name='few')) }}"
      termination_protection: no
      keypair: YOURKEYPAIRHERE
    register: ec2_out

  - name: wait for winrm
    wait_for:
      port: 5986
      host: "{{item.public_ip}}"
      timeout: 300
      state: started
    with_items: "{{ ec2_out.instances }}"

  - name: output IPs
    debug:
      msg: "System {{ item.dns_name }} with ip {{ item.public_ip}}"
    with_items: "{{ ec2_out.instances }}"

      # Borrowed heavily from youtube tutorial https://youtu.be/VRO9ZdH6Cbg

      # ansible_connection: winrm
      # ansible_winrm_transport: credssp
      # ansible_winrm_server_cert_validation: ignore
      # ansible_port: 5986
